version: '3'
services:
  base:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: go-fiddle-base

  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - base
      - kafka
    links:
      - kafka
    environment:
      KAFKA_SERVERS: kafka

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - base
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb
    environment:
      KAFKA_SERVERS: kafka
      MONGODB: mongodb://mongodb
      PORT: "8000"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    links:
      - zookeeper
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "username"
      MONGODB_PASS: "password"
